### ISSUE TITLE
Add CI test with cilium-cli

### ISSUE THREAD

**Issue by jrajahalme** [cilium/proxy#152]
Add a CI test workflow where each PR, release, and master thread is tested like this:

After `cilium/proxy` build for PR, release, or master is available, do:
- pull `cilium\cilium` master
- replace the reference to the new `cilium-envoy` into `images/cilium/Dockerfile`
- build cilium and operator images locally:
  - `DOCKER_IMAGE_TAG=test make docker-cilium-image docker-operator-generic-image`
- create a kind cluster:
  - `kind create cluster`
- load the locally built cilium images with the new `cilium-envoy`:
  - `kind load docker-image quay.io/cilium/operator-generic:test quay.io/cilium/cilium:test`
- pull latest master of `cilium/cilium-cli` & build locally
  - could also do the latest released version, but when adding new tests to cilium-cli, pulling the latest source is useful
- install cilium with `cilium-cli`, e.g. (while in the `cilium/cilium` directory)
  - `cilium install --chart-directory install/kubernetes/cilium --config monitor-aggregation=none --helm-set loadBalancer.l7.backend=envoy --helm-set tls.secretsBackend=k8s --agent-image=quay.io/cilium/cilium:test --operator-image=quay.io/cilium/operator-generic:test --helm-set image.pullPolicy=IfNotPresent --helm-set operator.image.pullPolicy=IfNotPresent --config debug=true --config debug-verbose=envoy`
   - `cilium hubble enable`
   - `cilium hubble port-forward&`
   - `cilium connectivity test`

**Comment by jrajahalme** [comment]
Bonus features: Allow triggering this from the PR comments so that you can choose the branch/commit SHA of either Cilium and/or cilium-cli to test against!

**Comment by mhofstetter** [comment]
@jrajahalme

are there specific reasons why we should enable and port-forward to hubble in this CI step?

**Comment by sayboras** [comment]
> are there specific reasons why we should enable and port-forward to hubble in this CI step?

This is mainly for validating the hubble flow as part connectivity test.
