### ISSUE TITLE
Build fails with spdlog 1.6.0

### ISSUE THREAD

**Issue by lgbaldoni** [cilium/proxy#21]
On openSUSE Tumbleweed, see [log](https://github.com/cilium/proxy/files/4643183/cilium_spdlog_160.txt).

**Comment by mrostecki** [comment]
1. This is an issue in Envoy's code (`source/extensions/filters/http/lua/lua_filter.cc` file belongs to Envoy source tree).
2. You can get rid of that error by adding `--copt="-Wno-switch" --cxxopt="-Wno-switch"` to `bazel build` command.
