### ISSUE TITLE
Building without Bazel or in a multi-stage container

### ISSUE THREAD

**Issue by smijolovic** [cilium/proxy#22]
Bazel is not an ideal build environment for building secure binaries. In fact this particular build process uses go 1.13.5 (7 versions behind the current go13 branch), and also fails to compile because ninja is not in the build environment (which also begs the question why two build environments). In addition, bazel include a slew of unnecessary dependencies with their own collection of vulnerabilities (is Java necessary to build a go/c/c++ microservice?)

With the increased threat of vulnerabilities appearing in microservice oriented projects, CNCF projects in general should be allowing developers that prioritize security a means to build projects such as these with only the necessary dependencies and compilers (gcc, make, go).

Can the team provide a means to build the envoy binary on the latest version of go?

**Comment by mrostecki** [comment]
@smijolovic

I think that we can address the problem with outdated Go by telling Bazel to use Go from host, which would probably require a small patch for Envoy, which would replace the following variable with the `"host"` value:

https://github.com/envoyproxy/envoy/blob/master/bazel/dependency_imports.bzl#L11

Regarding the necessity of using Bazel, I don't think we can avoid it. Java dependencies of Bazel should not affect the binary itself.

If you are concerned about C/C++ libraries (like libcurl, zlib etc.) being statically linked and bundled - there is a very hacky way of linking libraries dynamically which we use in openSUSE:

https://en.opensuse.org/Kubic:Development/ServiceMesh#Bazel
https://github.com/kubic-project/bazel-workspaces
https://build.opensuse.org/package/view_file/devel:kubic/envoy-proxy/envoy-proxy.spec?expand=1

To sum up that hack - Bazel allows to override dependencies with `--override_repository` option. To enforce dynamic linking, you can create Bazel config files (`WORKSPACE` and `BUILD`). For example, if you want to link zlib from system, you can use those files:

https://github.com/kubic-project/bazel-workspaces/blob/master/zlib/BUILD
https://github.com/kubic-project/bazel-workspaces/blob/master/zlib/WORKSPACE

and then call Bazel i.e. with `--override_repository="zlib=zlib/"` argument.

I was thinking about making that less hacky and push it upstream into Envoy codebase to provide an option for dynamic linking of some libraries. I didn't have time to do that yet, but I can try to find some time for that if you are interested. I think that would be beneficial for Linux distributions (Fedora, RHEL, Debian) which potentially would like to package Envoy without pulling in bundled libraries

**Comment by smijolovic** [comment]
How can we hack the proxy source to use the local host value for go?  I noticed that the most recent version of a bazel build (3.7.1) of cilium-envoy reports 1.14.5 which is 8 versions behind and has a bunch of CVEs:

[rpmbuild@localhost bazel-bin]$ ./cilium-envoy --version
./cilium-envoy  version: 6c980c60fb96e27faae370af792217316482c2ed/1.14.5/Modified/DEBUG/BoringSSL
