### ISSUE TITLE
Introduce release flow to follow Istio versions?

### ISSUE THREAD

**Issue by dntosas** [cilium/proxy#28]
Hello team!

I am wondering if it make sense this repo to follow version of Istio on releases so as people can pull Envoy as sidecar with Cilium intergation directly by changing Envoy image source in a friendly way.

For example: `docker pull cilium/istio-proxy:1.5 / 1.6 / 1.7 etc`

WDYT?

**Comment by errordeveloper** [comment]
I think it would indeed generally make sense, @jrajahalme should be able to tell more on what that might entail.

**Comment by jrajahalme** [comment]
Will look into this with 1.6 / 1.7 updates. So far we have wanted to move towards more specific tags rather than re-using tags from one release to another though.
