### ISSUE TITLE
Building proxy with envoy-openssl extensions

### ISSUE THREAD

**Issue by smijolovic** [cilium/proxy#31]
Would it be possible to tweak the bazel build of the proxy to use the envoy-openssl target vs envoy with boringSSL?

https://github.com/envoyproxy/envoy-openssl

**Comment by jrajahalme** [comment]
Cilium filters should have no boringSSL dependencies but in general we'll want to depend on official Envoy releases for timeliness of security updates, stability, etc. When/if it becomes an Envoy bootstrap/runtime option to use either BoringSSL or OpenSSL we'd be happy to add a Cilium configuration option for it.
