### ISSUE TITLE
Error inlined_vector.h -Werror=maybe-uninitialized

### ISSUE THREAD

**Issue by smijolovic** [cilium/proxy#34]
When building on CentOS8.2 with GCC 8.3.1, I get the following error:

make PKG_BUILD=1 V=$V DESTDIR=proxy-$BUILD_CILIUM_RELEASE cilium-envoy

ERROR: /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/476f2b41900750ece4c6f35941150caf/external/envoy/source/common/http/BUILD:265:17: C++ compilation of rule '@envoy//source/common/http:header_map_lib' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 122 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 122 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/com_google_absl/absl/container/inlined_vector.h:53,
                 from bazel-out/k8-opt/bin/external/envoy/include/envoy/http/_virtual_includes/header_map_interface/envoy/http/header_map.h:18,
                 from bazel-out/k8-opt/bin/external/envoy/source/common/http/_virtual_includes/header_map_lib/common/http/header_map_impl.h:9,
                 from external/envoy/source/common/http/header_map_impl.cc:1:
external/com_google_absl/absl/container/internal/inlined_vector.h: In member function 'void Envoy::Http::HeaderString::append(const char*, uint32_t)':
external/com_google_absl/absl/container/internal/inlined_vector.h:437:5: error: '<anonymous>.absl::inlined_vector_internal::Storage<char, 128, std::allocator<char> >::data_' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     data_ = other_storage.data_;
     ^~~~~
cc1plus: all warnings being treated as errors
Target //:cilium-envoy failed to build

In doing some research on envoy, I bumped into a bunch of issues that lead me to believe this might be a false-positive, and see that they added it to the cc_wrapper.py:
https://github.com/envoyproxy/envoy/issues/2987

How can we add the following:
-Wno-error=maybe-uninitialized or -Wno-maybe-uninitialized 
To the gcc compile flags?

**Comment by smijolovic** [comment]
so...

BAZEL_BUILD_OPTS ?= --jobs=3 --copt="-Wno-maybe-uninitialized"

In the Makefile provides a successful build.

If confirmed as a false positive it might make sense to add to the bazel code that provides the compiler options.

**Comment by jrajahalme** [comment]
You can do the `BAZEL_BUILD_OPTS ?= --jobs=3 --copt="-Wno-maybe-uninitialized"` on your `make` command line for an on-off build.

In general we'd not want to disable warnings for the whole build. Rather patch up the individual dependency that has a problem so that the build can be run with the intended settings, e.g., as in https://github.com/cilium/proxy/blob/master/patches/envoy-arm64.patch.
