### ISSUE TITLE
make docker-istio-proxy failed due to unknown flag: --load

### ISSUE THREAD

**Issue by yangyang198703** [cilium/proxy#58]
```
root@builder:/src/github.com/cilium/proxy# make docker-istio-proxy
DOCKER_BUILDKIT=1 docker build --load --build-arg BAZEL_BUILD_OPTS="" -f Dockerfile.istio_proxy -t cilium/istio_proxy:1.10.6 .
unknown flag: --load
See 'docker build --help'.
Makefile.docker:205: recipe for target 'docker-istio-proxy' failed
make: *** [docker-istio-proxy] Error 125
```

Docker version 20.10.8, build 3967b7d

Linux builder 4.15.0-1021-aws #21-Ubuntu SMP Tue Aug 28 10:23:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by GMsure** [comment]
Perhaps you can use `docker buildx verxion` to check if the buildx plugin is enabled ? I'm not sure, I solved a similar problem after installing the buildx plugin.

**Comment by sayboras** [comment]
Thanks for your issue, as well as the resolution. Custom istio image is no longer maintained for a while, we can just close this out.
